# Generated by Django 3.0.5 on 2023-04-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanagementapp', '0002_auto_20230429_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domitory', models.CharField(choices=[('Boys Dom A', 'Boys Dom A'), ('Boys Dom B', 'Boys Dom B'), ('Boys Dom C', 'Boys Dom C'), ('Girls Dom A', 'Girls Dom A'), ('Girls Dom B', 'Girls Dom B'), ('Girls Dom C', 'Girls Dom C')], default='Boys Dom A', max_length=25)),
            ],
        ),
    ]
