# Generated by Django 3.0.5 on 2023-04-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanagementapp', '0004_auto_20230429_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domitory',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='Session',
            field=models.CharField(choices=[('Day', 'Day'), ('Evening', 'Evening'), ('Weekend', 'Weekend')], default='Day', max_length=15),
        ),
    ]
